### ISSUE TITLE
Document time trigger retry behaviour

### ISSUE THREAD

**Issue by soamvasani** [fission/docs.fission.io#15]
Timer trigger retries a function when it fails.  Today it retries up to 10 times with an exponential delay starting at a half a second.  

We should document this behaviour, including how to tune it (see https://github.com/fission/fission/issues/660) 

We should also encourage people to test their functions with `fission fn test` before setting up a timer. Digging through timer logs is inherently more difficult than having an error happen while you're still setting things up.

**Comment by vishal-biyani** [comment]
Stale and closing for now.
