### ISSUE TITLE
Current URL should point to latest

### ISSUE THREAD

**Issue by vishal-biyani** [fission/docs.fission.io#16]
Currently if you go to website and navigate to any page, the URL has current version's number in the URL:

```https://docs.fission.io/0.7.0/usage/executor/```

Instead of this, it will be better to have `latest` in the URL so the if user bookmarks and visits later user will be redirected to latest version's page of the documentation.

```https://docs.fission.io/latest/usage/executor/```

Not sure if this is possible, but nice to have.

**Comment by soamvasani** [comment]
works this way now.
