### ISSUE TITLE
Access to router in Docker for Desktop works!

### ISSUE THREAD

**Issue by jonatasbaldin** [fission/docs.fission.io#166]
Hey there, how are u doing?

I'm using K8S from Docker from Desktop and, after creating a route for a function, the command `curl localhost:<port>/<url>` just works!

In the [docs](https://docs.fission.io/installation/install-docker-desktop/#docker-for-dekstop-specific-differences) it says it had a bug and instructs the user to do a port-forward, which maybe is not necessary anymore?

Here's my Docker for Desktop version:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/8570364/66970224-15d1a480-f063-11e9-92b4-eed2ef84eeb3.png">

If confirmed, I can work on a PR to remove or adapt the content of the doc 💃 

Cheers!

**Comment by life1347** [comment]
Hey @jonatasbaldin thanks for your report. 

I can confirm the problem was resolved. But one thing worth to notice and should add to the PR is

* Use service `port` (default port 80) if the service type is LoadBalancer; Otherwise, use following command to get the `nodePort`.

```
$ kubectl -n fission get svc router -o jsonpath='{.spec.ports[0].nodePort}'
```
