### ISSUE TITLE
Typo in docs/content/en/docs/concepts/components/core/assets/router.png

### ISSUE THREAD

**Issue by hadrien-toma** [fission/docs.fission.io#179]
There is a typo in the `HTTP requests` bloc, here is the fixed asset as an attached file:
![router](https://user-images.githubusercontent.com/6162030/71562172-31075a00-2a7f-11ea-8e44-6c76cb2be4b7.png)

**Comment by life1347** [comment]
@hadrien-toma thanks for your feedback. I will fix it soon.

**Comment by life1347** [comment]
Fixed.
