### ISSUE TITLE
Accessing multiple URL parameters

### ISSUE THREAD

**Issue by orfeas0** [fission/docs.fission.io#191]
Create an example with a route with multiple parameters.
What is the syntax?

**Comment by vishal-biyani** [comment]
Hi @orfeas0 Would [this for NodeJS](https://docs.fission.io/docs/languages/nodejs/#query-string) and [this for Go](https://docs.fission.io/docs/languages/go/#query-string) be helpful?

**Comment by vishal-biyani** [comment]
Related discussion here : https://github.com/fission/fission/issues/796

**Comment by orfeas0** [comment]
Thanks. Closing this as it's a doc issue, not functionality.
Doc PR: https://github.com/fission/docs.fission.io/pull/192
