### ISSUE TITLE
How to help translating

### ISSUE THREAD

**Issue by postor** [fission/docs.fission.io#200]
I want to learn fission by reading through docs, and why not translate them at the same time? so I fork and create a branch `translation-zh-hans` and PR? or how do you want i18n managed?

**Comment by vishal-biyani** [comment]
Hey @postor I am super familiar with i18 - but I think Hugo has supper for it. If you are aware please go ahead. If not, I will let you know by Monday.

**Comment by postor** [comment]
Hi Vishal, I already have hugo i18n working, and one page translated, I
just want to confirm how you guys want the languages managed,  like all
inside one branch, or in different branches, or in different repo?

Vishal <notifications@github.com> 于2020年5月2日周六 下午7:25写道：

**Comment by postor** [comment]
I just made a pull request to add chinese docs, supposing all languages in one branch, it's working and home page translated. @vishal-biyani
