### ISSUE TITLE
Ordering of listing in  document browser(left pane)

### ISSUE THREAD

**Issue by sanketsudake** [fission/docs.fission.io#273]
Our listing should be in the order

- Installation
- Using Fission
- Concepts
- Triggers
- Environments
- Examples
- Troubleshooting
- FAQs
- Contributing
- Release highlights

We need to compress the existing listing and also need to ensure it is in order for simplicity of browsing or seems natural to the new user.

**Comment by gauravgahlot** [comment]
As discussed the structure for new docs should be:

- Installation
  - Upgrade
  - Compatibility - Keda + Kubernetes (must be within installation page)
  - Uninstall
- Concepts
- Architecture (renaming components)
- Usage (using fission)
  - Functions - to be a list of what we have in using fission
  - Triggers
  - YAML Specs
  - Observability
  - Languages (Environment)
- Contributing
- Troubleshooting
- Releases
