### ISSUE TITLE
More complex examples

### ISSUE THREAD

**Issue by vishal-biyani** [fission/docs.fission.io#35]
Currently, most of the examples we have are a simple source file for a function. In the real world - things are more than a file. We need a few examples of main languages like Go, Python where we show a non-trivial example working as a function.

**Comment by soamvasani** [comment]
There are some slightly bigger examples in github.com/fission/faas-composition-patterns.  We can make a tutorial around that repo.

**Comment by soamvasani** [comment]
The samples are ready under github.com/fission, we should add a page with links to them.

**Comment by vishal-biyani** [comment]
Stale and closing
